version: "3.8"

services:
  db:
    image: mongo:3.6.1
    container_name: db
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    ports:
      - 27017:27017
    command: mongod
  logservice1:
    image: foreman1018/arep-taller6:db
    ports:
      - "7000:7000"
    container_name: logservice1
  logservice2:
    image: foreman1018/arep-taller6:db
    ports:
      - "7001:7000"
    container_name: logservice2
  logservice3:
    image: foreman1018/arep-taller6:db
    ports:
      - "7002:7000"
    container_name: logservice3
  Facade:
    image: foreman1018/arep-taller6:roundrobin
    ports:
      - "57000:57000"
    container_name: Facade
  

volumes:
  mongodb:
  mongodb_config: