FROM openjdk:17

WORKDIR /usrapp/bin

ENV PORT 7000

COPY /target/classes /usrapp/bin/classes
COPY /target/dependency /usrapp/bin/dependency


CMD ["java","-cp","./classes:./dependency/*","edu.eci.arep.mongo.taller6.AppLog"]